### ISSUE TITLE
Could lead to error mixing list attribute with literal attribute

### ISSUE THREAD

**Issue by mdogo** [cdelafuen/legion_bot#1]
https://github.com/cdelafuen/legion_bot/blob/90f7f01a848d60df8c07b6b025b878793efa8ebc/legion_bot/models.py#L101

You have defined COMMANDS as a literal there but as a list of literals above. It could be problematic having an attribute that sometimes is a list and sometimes a literal.

**Comment by cdelafuen** [comment]
Totally true, changing!
